imports:
  - { resource: "forms.yml" }

services:
  catalog-promotion.processor:
    class: SnakeTn\CatalogPromotion\Promotion\Processor
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('CatalogPromotionPlugin:Promotion')"
      - '@sylius.repository.promotion'
    calls:
      - [addRuleChecker,['has_taxon','@catalog-promotion.has-taxon-rule-checker']]

  catalog-promotion.has-taxon-rule-checker:
    class: SnakeTn\CatalogPromotion\Promotion\Checker\Rule\HasTaxonRuleChecker
    tags: [{name: catalog-promotion.rule-checker, type: has_taxon, label: Has at least one from taxons, form-type: Sylius\Bundle\CoreBundle\Form\Type\Promotion\Rule\HasTaxonConfigurationType}]

  catalog-promotion.has-option-rule-checker:
    class: SnakeTn\CatalogPromotion\Promotion\Checker\Rule\HasOptionRuleChecker
    tags: [{name: catalog-promotion.rule-checker, type: has_option, label: Has at least one from option values, form-type: SnakeTn\CatalogPromotion\Form\Type\Rule\HasOptionValueType}]

  catalog-promotion.registry_promotion_rule_checker:
    class: Sylius\Component\Registry\ServiceRegistry
    arguments:
      - SnakeTn\CatalogPromotion\Promotion\Checker\Rule\RuleCheckerInterface
      - rule checker

  catalog-promotion.form_registry.promotion_rule_checker:
    class: Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  catalog-promotion.channel-pricing-promotion-applicator:
    class: SnakeTn\CatalogPromotion\Promotion\Applicator\ChannelPricingPromotionApplicator

  sylius.calculator.product_variant_price:
    class: SnakeTn\CatalogPromotion\Promotion\ProductVariantPriceCalculator
    arguments:
      - '@catalog-promotion.processor'

  catalog-promotion.admin.menu_builder:
    class: SnakeTn\CatalogPromotion\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  catalog-promotion.form.type.promotion_rule_choice:
    class: SnakeTn\CatalogPromotion\Form\Type\PromotionRuleChoiceType
    arguments: [%catalog-promotion.promotion_rules%]
    tags:
      - { name: form.type}
