imports:
  - { resource: "forms.yml" }

services:
  catalog-promotion.processor:
    class: SnakeTn\CatalogPromotion\Promotion\Processor
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('CatalogPromotionPlugin:Promotion')"
      - '@sylius.repository.promotion'
    calls:
      - [addRuleChecker,['has_taxon','@catalog-promotion.has-taxon-rule-checker']]

  catalog-promotion.has-taxon-rule-checker:
    class: SnakeTn\CatalogPromotion\Promotion\Checker\Rule\HasTaxonRuleChecker
    tags: [{name: catalog-promotion.rule-checker, type: has_taxon, label: Has taxon, form-type: Sylius\Bundle\CoreBundle\Form\Type\Promotion\Rule\HasTaxonConfigurationType}]

  catalog-promotion.has-taxon-rule-checker2:
    class: SnakeTn\CatalogPromotion\Promotion\Checker\Rule\HasTaxonRuleChecker
    tags: [{name: catalog-promotion.rule-checker, type: has_taxon2, label: Has taxon2, form-type: Sylius\Bundle\CoreBundle\Form\Type\Promotion\Rule\HasTaxonConfigurationType}]

  catalog-promotion.channel-pricing-promotion-applicator:
    class: SnakeTn\CatalogPromotion\Promotion\Applicator\ChannelPricingPromotionApplicator

  sylius.calculator.product_variant_price:
    class: SnakeTn\CatalogPromotion\Promotion\ProductVariantPriceCalculator
    arguments:
      - '@catalog-promotion.processor'

  catalog-promotion.admin.menu_builder:
    class: SnakeTn\CatalogPromotion\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  catalog-promotion.form.type.promotion_rule_choice:
    class: SnakeTn\CatalogPromotion\Form\Type\PromotionRuleChoiceType
    arguments: [%catalog-promotion.promotion_rules%]
    tags:
      - { name: form.type}

  catalog-promotion.form.type.promotion_rule:
    class: SnakeTn\CatalogPromotion\Form\Type\PromotionRuleType
    arguments:
      - SnakeTn\CatalogPromotion\Entity\PromotionRule
      - [sylius]
      - '@sylius.form_registry.promotion_rule_checker'
    tags:
      - { name: form.type}
