services:
  catalog-promotion.processor:
    class: SnakeTn\CatalogPromotion\Promotion\Processor
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('CatalogPromotionPlugin:Promotion')"
      - '@sylius.repository.promotion'
    calls:
      - [addRuleChecker,['has_taxon','@catalog-promotion.has-taxon-rule-checker']]

  catalog-promotion.has-taxon-rule-checker:
    class: SnakeTn\CatalogPromotion\Promotion\Checker\Rule\HasTaxonRuleChecker

  catalog-promotion.channel-pricing-promotion-applicator:
    class: SnakeTn\CatalogPromotion\Promotion\Applicator\ChannelPricingPromotionApplicator

  sylius.calculator.product_variant_price:
    class: SnakeTn\CatalogPromotion\Promotion\ProductVariantPriceCalculator
    arguments:
      - '@catalog-promotion.processor'

  catalog-promotion.admin.menu_builder:
    class: SnakeTn\CatalogPromotion\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  catalog-promotion.form.type.promotion:
      class: SnakeTn\CatalogPromotion\Form\Type\PromotionType
      tags:
          - { name: form.type }
      arguments: ['SnakeTn\CatalogPromotion\Entity\Promotion']


  catalog-promotion.form.type.promotion_rule.collection:
      class: SnakeTn\CatalogPromotion\Form\Type\PromotionType
      tags:
          - { name: form.type }
      arguments: ['SnakeTn\CatalogPromotion\Entity\Promotion']

