sylius_resource:
    resources:
        app.catalog_promotion:
            driver: doctrine/orm
            classes:
                model: SnakeTn\CatalogPromotion\Entity\Promotion
                form: SnakeTn\CatalogPromotion\Form\Type\PromotionType
imports:
    - { resource: "@CatalogPromotionPlugin/Resources/config/grids/promotions.yml" }
